version: '3'

services:
  mongo:
    image: mongo
    restart: always
      #ports: 
      #  - "27017:27017"
    networks:
      - network
    volumes:
      - ./docker/mongo_data:/data/db

  redis:
    image: redis
    networks:
      - network
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis_data:/data

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    networks:
      - network
    env_file: ./backend/.env.dev
    depends_on:
      - mongo
      - redis
      - ml
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile.dev
    env_file: ./ml/.env.dev
    ports:
      - "50051:50051"
    networks:
      - network

networks:
  network: {}

volumes:
  node_modules: {}
