version: '3'

vars:
  test_redis_container: test-redis

tasks:

  setup: 
    cmds:
      - cmd: docker run -d -p 6379:6379 --name {{.test_redis_container}} -v .\\docker\\redis-data:\\redis-data\\ redis
        ignore_error: true
      - cmd: docker restart {{.test_redis_container}} 
        ignore_error: true


  clean:
    cmds:
      - cmd: docker stop {{.test_redis_container}}
        ignore_error: true
        #- docker rm -f {{.test_redis_container}} 

  build:
    cmds:
      - npm run build

        #prof:
        #  deps: [clean]
        #  cmds:
        #    - task: setup
        #      #- node --prof ./dist/app.js
        #    - 0x -o ./dist/app.js

  dev: # wasn't able to setup hot reload with docker compose so using this to simulate the dev env.
    deps: [clean]
    cmds:
      - task: setup
      - npm run dev

  test:
    deps: [clean]
    env:
      NODE_ENV: development
    cmds:
      - task: setup
      - npm test
      - task: clean

  test_file:
    deps: [clean]
    env:
      NODE_ENV: test
    cmds:
      - task: setup
      - npm test -- {{.CLI_ARGS}}
      - task: clean

