name: 'Update PGRKAM Data'

on: 
  schedule:
    - cron: '0 * * * *' # minute hour day-of-month month day-of-week

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make Api Request
        run: |
          BASE_URL=${{secrets.BACKEND_BASE_URL}}
          API_KEY=${{secrets.API_KEY}}
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-jobs?type=private&apiKey=$API_KEY")
          echo "Response from update-jobs (private): $response"
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-jobs?type=public&apiKey=$API_KEY")
          echo "Response from update-jobs (public): $response"

          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-filter-values?type=experience&apiKey=$API_KEY")
          echo "Response from update-filter-values (experience): $response"
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-filter-values?type=qualification&apiKey=$API_KEY")
          echo "Response from update-filter-values (qualifications): $response"
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-filter-values?type=state-district&apiKey=$API_KEY")
          echo "Response from update-filter-values (states-districts): $response"
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-filter-values?type=job-type&apiKey=$API_KEY")
          echo "Response from update-filter-values (job-types): $response"
          response=$(curl -s -H "Authorization: Bearer $API_KEY" "$BASE_URL/api/v1/cron/update-filter-values?type=job-title&apiKey=$API_KEY")
          echo "Response from update-filter-values (job-titles): $response"
